  
POST http://localhost:3000/server/submit
Content-Type: application/json

{
    "title":"Hello",
    "author":"Is it you",
    "year":"2021",
    "sePracticeFull":"awngln",
    "sePracticeShort":"Hi Hi",
    "claim":"short",
    "evidenceStrength":"HI HI HI"
}