# This is a basic workflow to help you get started with Actions

name: Node Continuous Integration

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]


jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install frontend dependencies
        working-directory: register
        run: npm install
      - name: Install backend dependencies
        working-directory: registerbackend
        run: npm install
      - name: Test frontend
        working-directory: register
        run: npm test
