# This is a basic workflow to help you get started with Actions

name: Node Continuous Integration

on:
  pull_request:
    branches: [ main ]


jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - run: cd register
      - run: npm test
      - run: cd ../registerbackend
      - run: npm test
      - run: npm run build
